# Site settings
title: Obsession of Moments
SEOTitle: Obsession of Moments | Amir's Blog
header-img: img/death_stranding_rope_stick.png
email: huxpro@gmail.com
description: "总而言之不醒。"
keyword: "Amir, Amir的博客, Amir's Blog, 博客, 个人网站, 互联网, Web, Economics, 经济, Statistics, 统计, 记录, Obsession of Moments"
url: "https://amir0320.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
github_username:   amir0320
twitter_username:   AmirNie
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: false                         # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: Canada/Eastern



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: amirnie

# Analytics settings
# Google Analytics
ga_track_id: G-PKF3R60RB1           # Format: UA-xxxxxx-xx
ga_domain: https://amir0320.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Just trying to get my shit together."
sidebar-avatar: /img/me.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
        title: "Marginal Revolution",
        href: "https://marginalrevolution.com/"
    },{
        title: "Wait But Why",
        href: "https://waitbutwhy.com/"
    },{
        title: "Gapminder",
        href: "https://www.gapminder.org/"
    }
]
